// let number = Math.floor((Math.random() * 100) + 1); // Generates a random number b/w 1 and 100
// let chances = 0; // Initial vaulue of chances taken to guess a number
// let guess; // Variable to store the number to be input from user to be guessed

// console.log("This is a guessing game and you have to enter a number and if it matches with the number generated by computer, then you win...\n");
// guess = prompt("Enter a number between 1 and 100");
// ++chances; // To increment the number of chances taken

// do {
//   guess = Number.parseInt(guess);

//   if (guess > number) {
//     console.log("Number entered is greater");
//     guess = prompt("Enter again!!");
//     guess = Number.parseInt(guess);
//     ++chances; // To increment the number of chances taken
//     continue;
//   }

//   else if (guess < number) {
//     console.log("Number entered is smaller");
//     guess = prompt("Enter again!!");
//     guess = Number.parseInt(guess);
//     ++chances; //To increment the number of chances taken
//     continue;
//   }

// } while (guess != number); //break the loop if number entered is equal to the number generated

// let score = 100 - chances; //To store the score of your game
// console.log("\nCongratulations🥳🥳\nThe number generated was", number + " and you guessed it right😁\nYour final score is", score);





// this is another one 


let number = Math.floor((Math.random() * 100) + 1);
let chances = 0;
let guess;

console.log("This is a guessing game and you have to enter a number between 1 and 100.\n");

do {
  guess = prompt("Enter a number between 1 and 100");
  guess = Number.parseInt(guess);

  if (isNaN(guess) || guess < 1 || guess > 100) {
    console.log("Invalid input. Please enter a number between 1 and 100.");
    continue;
  }

  chances++;

  if (guess > number) {
    console.log("Number entered is greater.");
  } else if (guess < number) {
    console.log("Number entered is smaller.");
  }

} while (guess !== number);

let score = 100 - chances;
console.log("\nCongratulations 🥳🥳");
console.log("The number generated was", number, "and you guessed it right! 😁");
console.log("Your final score is", score);